language: ruby
rvm:
  - 1.9.3
script:
  - bundle exec rspec
notifications:
  campfire:
    rooms:
      secure: H6dWBB9lw65AwG951x+jNzj7nMI0FAHN/W1ZzQ+93hPW1mUHm3EK028JsEROSqNG1dMG4dm+UB1MPds4wtHWJNBjkcQO5qglCxWkWwUADcTMSkmAL7OcY59LkfXPa+Eqw1dGnhDZqA7EQuFWXIXnbV/EazadvpHHucbNzipDJrw=
    template:
      - "%{repository}#%{build_number} %{message} (%{branch} - %{commit} : %{author}) Change view : %{compare_url} Build details : %{build_url}"
    on_success: change
    on_failure: always
